name: kids_drawing_app
description: A drawing app

publish_to: 'none'

version: 2.0.2+2

environment:
  sdk: ">=2.16.2 <3.10.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  flutter_svg: ^1.0.3
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/eraser.svg
    - assets/images/pencil.svg
    - assets/pointers/pencil_pointer.svg

