name: kids_drawing_app
description: A drawing app

publish_to: 'none'

version: 2.0.2+2

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3
  go_router: ^13.2.0
  flutter_native_splash: ^2.3.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/logos/

flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/pendraw_logo.png
  color_dark: "#121212"

  android_12:
    image: assets/logos/pendraw_logo.png
    icon_background_color: "#ffffff"

  web: false

